# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20190209_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сайт для поиска')),
            ],
            options={
                'verbose_name': 'Сайт для поиска',
                'verbose_name_plural': 'Сайты для поиска',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.CharField(max_length=250, unique=True, verbose_name='Адрес для поиска')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='Город')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Site', verbose_name='Сайт для поиска')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Адрес для поиска',
                'verbose_name_plural': 'Адресa для поиска',
            },
        ),
    ]
